apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mealie
  name: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
status:
  loadBalancer: {}
